### PR TITLE
Implement alternate colorscheme option for accessibility (resolves #10)

### LINKED ISSUE #10: [Feature Request] Multiple Colorschemes
It would be great if I could change the colorscheme. It's very difficult for me to distinguish red and green.

### PR DESCRIPTION
**Pull request by ywnico**
- Add a new setting, which allows the user to switch between two colorschemes
- Colorscheme preference is an int (0 = default, 1 = accessible), so that if it were desired to add colorschemes later (e.g., for dark theme), it would be easy to do so.
- Update texture.xcf to include a second set of colors
- Expand texture images from 2048x2048 to 2048x2172 to accommodate the additional settings entry
- Each drawable-nodpi dir now has 2 texture files: texture_colorscheme_0.png (the original) and texture_colorscheme_1.png.

I hope this is an acceptable solution which is not too complicated. I don't have much experience with Java and Android development, but since I mostly followed ByteHamster's existing code (e.g., copying settings buttons) I hope it is ok. I can make any suggested changes, of course.

I did fear I might possibly be breaking ByteHamster's style of keeping everything very clean and separated in `SettingsState.java` lines 31 & 45-46, where I saved the `glRenderer` variable so that `glRenderer.setColorscheme` could be called from `onTouchEvent`. But I did not think of an alternative.

### CODE REVIEW

**Comment by ByteHamster** [comment]
Thanks! Is there a way to re-order the items instead of resizing? I'm not entirely sure which version of OpenGL we are using, but I think we are using 1.0.
OpenGL 1.0 does not support textures of arbitrary size, so I think making the texture slightly larger like your change actually makes it 4 times larger internally.

**Comment by ywnico** [comment]
Oh, I didn't realize that. Indeed, there's enough blank space to rearrange the textures and keep it within 2048x2048 (I did also need to move the volume icons and header background).

**Comment by ByteHamster** [comment]
Thanks for updating! Would it somehow be possible to re-load the texture when changing the setting instead of always keeping both textures in memory? I don't know too much about OpenGL, but it feels like that should be somehow possible

**Comment by ywnico** [comment]
That does make sense, especially if there were more colorschemes.... I will look into how to do that.

**Comment by ywnico** [comment]
This update should solve the problem of loading textures when changing colors instead of preloading them.

**Comment by ByteHamster** [comment]
Awesome, thanks!

**Pull request merged**
